### ISSUE TITLE
Forgive me for being a total noob/idiot, but how do I go about building/running this utility?

### ISSUE THREAD

**Issue by glyko** [Zaczero/League-of-Legends-FPS-Capper#1]
I recently came across this tool and it looks like exactly what I am looking for. However, I have no real knowledge of how to use Github/programming in general. I can't figure out how to turn this project on Github I can actually run on my PC and I would really appreciate some help in figuring this out.

Kind regards

**Comment by Zaczero** [comment]
[League of Legends FPS Capper.zip](https://github.com/Zaczero/League-of-Legends-FPS-Capper/files/1616574/League.of.Legends.FPS.Capper.zip)

Attached a builed binary.
Just let me know if this still works.
Haven't used it for a while and it's possible that it's outdated :)
In this case I'll update it within a day ;)

**Comment by glyko** [comment]
I don't want to be disrespectful or anything, but the file you just uploaded is immediately blocked by Windows Defender as a Virus...

**Comment by Zaczero** [comment]
Well, it's open source (you can view the code lolz) and the version I've sent to you is not obfuscated in any way. Mostly a false positive.

**Comment by glyko** [comment]
I agree with that, but unfortunately, I do not have the knowledge to understand if there is anything malicious going on or not. As I stated above, I am a total noob :/ Because of this, I just do not feel comfortable running the application.

**Comment by Zaczero** [comment]
Do what you want
